### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by axaluss** [scalatra/sbt-scalatra#20]
```
> container:start
#[info] Updating {file:/home/nyxos/IdeaProjects/GUS/gus-tools-server/}gus-tools-server...
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.1 ...
[info] Done updating.
[info] Compiling Templates in Template Directory: /home/nyxos/IdeaProjects/GUS/gus-tools-server/src/ma
in/webapp/WEB-INF/templates
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I tried to add 

```
        "org.slf4j" % "slf4j-api" % "1.7.13",
        "ch.qos.logback" % "logback-classic" % "1.0.13"
```

or 

```
        "org.slf4j" % "slf4j-api" % "1.7.13",
        "org.slf4j" % "slf4j-simple" % "1.7.13"
```

to the build.sbt and project/build.scala 

but neither of them remove the error.

**Comment by dozed** [comment]
Can you try `jetty:start`?

**Comment by hcwilhelm** [comment]
I have the same problem. Yes I can reach the webserver with my browser. If you know how to solve
this let me know.

**Comment by axaluss** [comment]
i switched to spray

**Comment by miccagiann** [comment]
Installation does not work for Windows 7 although I am using the powershell script.
More specifically, I execute the following command mentioned in the book "Scalatra in Action":
>g8.bat scalatra/scalatra-sbt
Project is created successfully.
When executing the following commands:
>sh sbt
>jetty:start (inside sbt shell)
I face the error: java.lang.NoClassDefFoundError: org.slf4j.impl.StaticLoggerBinder
                         Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder

Is there any plan this issue to be fixed for Windows 7 systems. If not, can you provide any hints on how to work around this issue. If not can you point me  to the correct direction? Any hint is more than welcomed. In Ubuntu 14.04 LTS I have absolutely no problem at all.

Thanks,
Michael

**Comment by sbl1996** [comment]
I have the same problem too.  I am gonna be mad!!

**Comment by magnolia-k** [comment]
In the current version of sbt - scalatra, if you add logback as a dependency, logs are output normally.

For details, refer to the sample code build.sbt

https://github.com/scalatra/scalatra-website-examples
