### ISSUE TITLE
OverlayWars does not recognize unmanaged war file

### ISSUE THREAD

**Issue by magnolia-k** [scalatra/sbt-scalatra#37]
Although the overlayWars task lists libraries, it only covers managed libraries, not unmanaged libraries.

Since the war file is generally an application, it is supposed to be an unmanaged library.

Should the overlayWars task be searched for unmanaged libraries under the lib directory?

**Comment by takezoe** [comment]
Hmm... I'm not sure about the war-overlay plugin. What situation should we use it?

**Comment by magnolia-k** [comment]
It seems to be used as packaging by replacing the war file of the subproject.
In maven, explicitly specify it.

https://maven.apache.org/plugins/maven-war-plugin/overlays.html


Since there is not any document in the first place in the first place, it seems that few people use it.

**Comment by takezoe** [comment]
Thanks, I got it. I think it should support war files in unmanaged libraries. However I'm wondering whether scalatra-sbt plugin should support war overlay in the first place. :thinking:

**Comment by magnolia-k** [comment]
Well, I think that it may be separated from Scalatra-sbt in the first place.

**Comment by magnolia-k** [comment]
https://github.com/scalatra/sbt-scalatra/pull/48

I think that it is better to continue modifying future functions in another repository.
