### ISSUE TITLE
Artifactory fails to transform pom file

### ISSUE THREAD

**Issue by feyyaz-ertugrul** [scalatra/sbt-scalatra#54]
We are using an internal artifactory which is a mirror of Maven Central Repository.

The `sbt-scalatra-1.0.1.pom` file in Maven Central looks OK, but our local artifactory returns the below error message as the content.

```
{
  "errors" : [ {
    "status" : 404,
    "message" : "Failed to transform pom file: The target deployment path 'org/scalatra/sbt/sbt-scalatra_2.12_1.0/1.0.1/sbt-scalatra-1.0.1.pom' does not match the POM's expected path prefix 'org/scalatra/sbt/sbt-scalatra/1.0.1'. Please verify your POM content for correctness and make sure the source path is a valid Maven repository root path."
  } ]
}

```

After googling a bit, I see that there is a feature called "Suppress POM Consistency Check" in artifactory, the problem would be resolved when this feature is turned on. But I want to understand if there is anything that can be done on the project side, instead of suppressing consistency checks.

I cannot suggest a solution as I'm not a maven expert, but I found another library which has almost the same structure and works fine. The differences are it has maven-metadata.xml on its parent folder, and also the naming of the pom file contains scala version as well:

**URL**: http://central.maven.org/maven2/com/timushev/scalatags-rx_sjs0.6_2.12/0.3.0/
**Name of the pom file**: scalatags-rx_sjs0.6_2.12-0.3.0.pom

**Comment by magnolia-k** [comment]
Although it does not become a direct solution, I found a case where the Artifact name includes both the major version of Scala and the major version of sbt, and similar events occurred.

https://github.com/coursier/coursier/issues/286

Rather than the problem of sbt-scalatra, it seems to be a problem of artifactory 's path check (it seems to make two underscores an error)
