### ISSUE TITLE
Jetty Version is out of date 

### ISSUE THREAD

**Issue by petermcneil** [scalatra/sbt-scalatra#69]
The Jetty version used when running `jetty:start` is out of date and fails to run with newer versions of the JDK.

Current version: 9.4.8.v20171121

This is due to the underlying plugin being out of date.

`com.earldouglas.xsbt-web-plugin`
Version: 4.0.2

The latest version of this plugin uses a version that will support newer JDKs.
Updated jetty version: 9.4.20.v20190813

**Comment by takezoe** [comment]
Thanks for reporting. We will upgrade xsbt-web-plugin.
